Repository GSG-G11/wasslni-app, pull requests merged in 2022-05, with the labels that each got.

#4 file structure in client side
  client/.expo-shared/assets.json
  client/.gitignore
  client/App.js
  client/app.json
  client/assets/adaptive-icon.png
  client/assets/favicon.png
  client/assets/icon.png
  client/assets/splash.png
  client/babel.config.js
  client/components/Card/Card.jsx
  client/components/Form/Form.jsx
  client/components/Map/Map.jsx
  client/components/Property/Property.jsx
  client/components/SideBar/SideBar.jsx
  client/components/Toast/Toast.jsx
  client/components/UI/Button/Buttom.jsx
  client/components/UI/Input/Input.jsx
  client/components/UI/Loader/Loader.jsx
  client/components/UI/Logo/Logo.jsx
  client/components/UI/Select/Select.jsx
  client/components/UI/Title/Title.jsx
  client/components/UI/index.js
  client/components/index.js
  client/package-lock.json
  client/package.json
  client/screens/Home/Home.jsx
  client/screens/Login/Login.jsx
  client/screens/ParcelDetails/ParcelDetails.jsx
  client/screens/Parcels/Parcels.jsx
  client/screens/Profile/Profile.jsx
  client/screens/SMS/SMS.jsx
  client/screens/Signup/Signup.jsx
  client/screens/index.js
Labels: Awaiting Review

#8 create loader
  client/components/UI/Loader/Loader.jsx
Labels: Awaiting Review

#9 create title component
  client/App.js
  client/components/UI/Title/Title.jsx
  client/components/UI/index.js
  client/components/index.js
  client/package-lock.json
  client/package.json
Labels: Awaiting Review

#17 create error message component
  client/App.js
  client/components/Form/ErrMsg/ErrMsg.jsx
  client/components/Form/index.jsx
  client/components/index.js
Labels: approved

#13 create button component
  client/App.js
  client/components/UI/Button/Buttom.jsx
  client/components/UI/index.js
  client/components/index.js
Labels: Awaiting Review

#21 create generic input component with formik
  client/components/Form/ErrMsg/ErrMsg.jsx
  client/components/UI/Input/Input.jsx
  client/package-lock.json
Labels: approved

#23 Create User Context
  client/App.js
  client/context/userContext.js
  client/package-lock.json
  client/package.json
  client/utils/index.js
  client/utils/userInfo/getUserInfo.js
Labels: approved

#37 31 property component
  client/components/Property/Property.jsx
  package.json
Labels: Awaiting Review

#35 create parcel screen
  client/App.js
  client/components/Card/Card.jsx
  client/components/UI/index.js
  client/components/index.js
  client/package-lock.json
  client/screens/Parcels/Parcels.jsx
  client/screens/index.js
  package-lock.json
Labels: Awaiting Review

#36 create profile screen
  client/App.js
  client/components/index.js
  client/package-lock.json
  client/package.json
  client/screens/Login/Login.jsx
  client/screens/Profile/Profile.jsx
  client/screens/index.js
Labels: Awaiting Review

#41 create parcel details
  client/App.js
  client/components/Card/Card.jsx
  client/components/Property/Property.jsx
  client/components/index.js
  client/screens/Login/Login.jsx
  client/screens/ParcelDetails/ParcelDetails.jsx
  client/screens/Parcels/Parcels.jsx
  client/screens/index.js
Labels: Awaiting Review

#42 38 create add parcel form
  client/App.js
  client/package-lock.json
  client/package.json
  client/screens/AddParcel/AddParcel.js
  client/screens/Parcels/Parcels.jsx
  client/screens/index.js
  client/utils/index.js
  client/utils/validation/parcel/addParcelSchema.js
Labels: Awaiting Review

#44 create nav bar
  client/App.js
  client/components/Card/Card.jsx
  client/package-lock.json
  client/package.json
  client/screens/AddParcel/AddParcel.js
  client/screens/Logout/Logout.jsx
  client/screens/MainContainer.js
  client/screens/ParcelDetails/ParcelDetails.jsx
  client/screens/Parcels/Parcels.jsx
  client/screens/index.js
Labels: Awaiting Review

#46 style screens
  client/App.js
  client/components/Card/Card.jsx
  client/components/Property/Property.jsx
  client/screens/AddParcel/AddParcel.jsx
  client/screens/Home/Home.jsx
  client/screens/Login/Login.jsx
  client/screens/MainContainer.js
  client/screens/ParcelDetails/ParcelDetails.jsx
  client/screens/Parcels/Parcels.jsx
Labels: Awaiting Review

#48 create readme
  README.md
Labels: Done
